[build]
command = ""            # sin build
publish = "."
functions = "functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[dev]
command = ""            # no lanzar frontend en dev
port = 8888
targetPort = 0
functionsPort = 9999
